### ISSUE TITLE
script not yet approved for use

### ISSUE THREAD

**Issue by SVilgelm** [tabeyti/jenkins-jack#14]
Hi, I'm trying to execute a pipeline, but got this error:
```java
org.jenkinsci.plugins.scriptsecurity.scripts.UnapprovedUsageException: script not yet approved for use
	at org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval.using(ScriptApproval.java:474)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition.create(CpsFlowDefinition.java:120)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition.create(CpsFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:299)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```
What script should be approved?

**Comment by SVilgelm** [comment]
The problem in the scriptsecurity plugin.

**Comment by DDD0311** [comment]
what was thefix for this one?

**Comment by SVilgelm** [comment]
sorry, I don't remember :)

**Comment by aspirelus** [comment]
For anyone that had this issues this is the solution I came up with :
Go to JenkinsGUI -> Manage Jenkins -> In-process Script Approval -> Approve your script to run
