### ISSUE TITLE
Could not connect to the remote Jenkins

### ISSUE THREAD

**Issue by Wasp3r** [tabeyti/jenkins-jack#59]
Hello,

I have an error trying to connect to my remote Jenkins. It looks like an issue that was already solver:
https://github.com/tabeyti/jenkins-jack/issues/43
I've installed vsix mentioned in this issue, upgraded to 1.1.3 but nothing helped. I see Nodes, but nothing moore.

![image](https://user-images.githubusercontent.com/26937064/117410436-b2dc8280-af12-11eb-8875-9a4d6893cc55.png)

**Comment by fabianosan** [comment]
I have the same issue, the extension connects to Jenkins instance, load nodes/agents information, but can't load jobs and pipelines!

After an investigation, I found tha the problem is with the jenkins API call from the extension, when Jenkins was installed in some new web servers, like Apache TomCat 7+ for Windows Server and others, that do some RFC standard validations and if the http call not meet this validations, an error 400 is throw.

**Here is more information about the issue and a workaround solution until the extension is fixed:**
https://stackoverflow.com/questions/41053653/tomcat-8-is-not-able-to-handle-get-request-with-in-query-parameters

![image](https://user-images.githubusercontent.com/288190/124179822-bbbc8100-da89-11eb-9adb-ba5387a4a7cc.png)

**And here is the Developer Tools console output:**
StatusCodeError: 400 - "<!doctype html><html lang=\"en\"><head><title>HTTP Status 400 – Bad Request</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1><hr class=\"line\" /><p><b>Type</b> Exception Report</p><p><b>Message</b> Invalid character found in the request target [&#47;JENKINSCI&#47;api&#47;json?tree=jobs[name,fullName,url,buildable,inQueue,description,jobs[name,fullName,url,buildable,inQueue,description,jobs[name,fullName,url,buildable,inQueue,description]]]]. The valid characters are defined in RFC 7230 and RFC 3986</p><p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p><p><b>Exception</b></p><pre>java.lang.IllegalArgumentException: Invalid character found in the request target [&#47;JENKINSCI&#47;api&#47;json?tree=jobs[name,fullName,url,buildable,inQueue,description,jobs[name,fullName,url,buildable,inQueue,description,jobs[name,fullName,url,buildable,inQueue,description]]]]. The valid characters are defined in RFC 7230 and RFC 3986\r\n\torg.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:490)\r\n\torg.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261)\r\n\torg.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)\r\n\torg.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)\r\n\torg.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)\r\n\torg.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\r\n\tjava.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tjava.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\torg.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\r\n\tjava.lang.Thread.run(Unknown Source)\r\n</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class=\"line\" /><h3>Apache Tomcat/9.0.41</h3></body></html>"
	at new StatusCodeError (c:\Users\<USER>\.vscode\extensions\tabeyti.jenkins-jack-1.1.5\node_modules\request-promise-core\lib\errors.js:32:15)
	at Request.plumbing.callback (c:\Users\<USER>\.vscode\extensions\tabeyti.jenkins-jack-1.1.5\node_modules\request-promise-core\lib\plumbing.js:104:33)
	at Request.RP$callback [as _callback] (c:\Users\<USER>\.vscode\extensions\tabeyti.jenkins-jack-1.1.5\node_modules\request-promise-core\lib\plumbing.js:46:31)
	at Request.self.callback (c:\Users\<USER>\.vscode\extensions\tabeyti.jenkins-jack-1.1.5\node_modules\request\request.js:185:22)
	at Request.emit (events.js:315:20)
	at Request.<anonymous> (c:\Users\<USER>\.vscode\extensions\tabeyti.jenkins-jack-1.1.5\node_modules\request\request.js:1161:10)
	at Request.emit (events.js:315:20)
	at IncomingMessage.<anonymous> (c:\Users\<USER>\.vscode\extensions\tabeyti.jenkins-jack-1.1.5\node_modules\request\request.js:1083:12)
	at Object.onceWrapper (events.js:421:28)
	at IncomingMessage.emit (events.js:327:22)
	at endReadableNT (internal/streams/readable.js:1327:12)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by solvingj** [comment]
@fabianosan What can be done in JenkinsJack to work around this?

**Comment by jmarandet** [comment]
same kind of issue, the plugin is not working anymore.
VSCode 1.65.2
Jenkins 2.332.1

**Comment by Gexar** [comment]
Same problem here
VSCode 1.64.2
Jenkins 2.263.3

**Comment by hoppfrosch** [comment]
Problem still exists here

* On VSCode startup  _"Could not connect to the remote Jenkins"_ **ALWAYS**  occurs - unless I configured a valid Jenkins-Connection in previous run, which works without any flaws then.
* On the VSCode-Notifikatiobn "Could not connect to the remote Jenkins" I press the button "Edit Connection"
*  VSCode asks for the connection parameters - as a default the previously entered (and working!!) connection parameters are offered
*  Confirming each of the offered connection parameter by simply pressing return connects to  my Jenkins again

Summary: On startup, connection to stored remote Jenkins fails -  unless the connection parameters are correct
