### ISSUE TITLE
Always report 'Could not connect to the remote Jenkins'

### ISSUE THREAD

**Issue by tiansin** [tabeyti/jenkins-jack#9]
My jenkins is running manually, and many times I don't need to start it, but the plugin always reports me wrong.

**Comment by tabeyti** [comment]
Hey @tiansin . Sorry for the late reply. I think you are referring to an issue where the `Could not connect to the remote Jenkins` would always show when opening vscode or updating settings, even if you had correct connection information.

This should be fixed in the latest release [1.0.1](https://github.com/tabeyti/jenkins-jack/blob/master/CHANGELOG.md#fixed)

Please let me know if this is what you were referring to and thanks for submitting the issue 👍

**Comment by tabeyti** [comment]
Closing issue

**Comment by mhagnumdw** [comment]
@tabeyti , I have the same, always "Could not connect to the remote Jenkins".

vscode version: 1.50.0
OS: Windows 10 Pro
Jenkins Jack version: 1.1.0
Jenkins version: 2.32.3

**My vscode settings.xml**

```json
  "jenkins-jack.jenkins.connections": [
    {
      "name": "My Jenkins",
      "uri": "http://my.address.com.br",
      "username": "my-user",
      "password": "my-password",
      "active": true
    }
  ]
```

**Errors in the vscode console (Developer Tools)**

```console
console.ts:137 [Extension Host] RequestError: Error: getaddrinfo ENOTFOUND f0692311	at new RequestError (c:\Users\myuser\.vscode\extensions\tabeyti.jenkins-jack-1.1.0\node_modules\request-promise-core\lib\errors.js:14:15)	at Request.plumbing.callback (c:\Users\myuser\.vscode\extensions\tabeyti.jenkins-jack-1.1.0\node_modules\request-promise-core\lib\plumbing.js:87:29)	at Request.RP$callback [as _callback] (c:\Users\myuser\.vscode\extensions\tabeyti.jenkins-jack-1.1.0\node_modules\request-promise-core\lib\plumbing.js:46:31)	at self.callback (c:\Users\myuser\.vscode\extensions\tabeyti.jenkins-jack-1.1.0\node_modules\request\request.js:185:22)	at Request.emit (events.js:223:5)	at Request.onRequestError (c:\Users\myuser\.vscode\extensions\tabeyti.jenkins-jack-1.1.0\node_modules\request\request.js:881:8)	at ClientRequest.emit (events.js:228:7)	at Socket.socketErrorListener (_http_client.js:406:9)	at Socket.emit (events.js:223:5)	at emitErrorNT (internal/streams/destroy.js:92:8)	at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)	at processTicksAndRejections (internal/process/task_queues.js:81:21)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'filter' of undefined
t.log @ console.ts:70
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read property 'filter' of undefined	at NodeTreeProvider.<anonymous> (c:\Users\myuser\.vscode\extensions\tabeyti.jenkins-jack-1.1.0\out\nodeTree.js:60:27)	at Generator.next (<anonymous>)	at fulfilled (c:\Users\myuser\.vscode\extensions\tabeyti.jenkins-jack-1.1.0\out\nodeTree.js:5:58)	at processTicksAndRejections (internal/process/task_queues.js:94:5)
t.log @ console.ts:70
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'filter' of undefined
$onExtensionRuntimeError @ terminalInstanceService.ts:31
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'filter' of undefined
	at NodeTreeProvider.<anonymous> (c:\Users\myuser\.vscode\extensions\tabeyti.jenkins-jack-1.1.0\out\nodeTree.js:60:27)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\myuser\.vscode\extensions\tabeyti.jenkins-jack-1.1.0\out\nodeTree.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
```

@tabeyti, can this issue be reopened? Is there a more appropriate log somewhere?

Tks!
